server:
  port: 11002
spring:
  application:
    name: product
  cloud:
    config:
      discovery:
        service-id: configServer
        enabled: true
      profile: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/

